@startuml
skinparam DefaultFontName "Lucida Sans Typewriter"

skinparam Activity{
    BackgroundColor snow
    BorderColor DarkSlateBlue
    DiamondBackgroundColor ghostwhite
    DiamondBorderColor DarkSlateBlue

}
skinparam Note{
    BorderColor DarkSlateBlue
    BackgroundColor LightYellow
}

skinparam ArrowColor DarkSlateBlue

start
note left 
Komplexere Entscheidungen
werden durch Notiz mit 
dem Stereotyp 
<<decision input>>
erläutert.
end note
note right
<<decision input>>
Ist hinreichend 
Bonität vorhanden?
end note
 if() then ([true])
:Kaufvertrag abwickeln;
else ([false])
:zunächst Beratung anbieten;
endif
stop
	
@enduml
