@startuml
' Welche Schriften gibt es auf dem System?
' listfonts als plantUML-Kommando gibt's aus.
skinparam DefaultFontName "FG Virgil"
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false


  |Customer|
  |Dev|
  |QM|
  |Customer|
  start
  repeat
  :add Requirment;
  |Dev|
  fork
    :ask Customer>
	Detach
	:get response<
  fork again 
  :test;
  fork again
  :deploy;
  end
  fork again 
  |QM|
    :Review;
  end fork
   |Customer|
     repeat while () is ([open tasks])
->[finished];
|Dev|
stop 
@enduml
