@startuml
    |QM|
  |Dev|
  |Customer|
  start
  repeat
  :add Requirment;
  |Dev|
  fork
    |QM|
    :Review;
    |Dev|
    fork again 
    :ask Customer>
	Detach
	:get response<
  fork again 
  :test;
  fork again
  :deploy;
  end
 |Dev|
  end fork
   |Customer|
     repeat while () is ([open tasks])
->[finished];
|Dev|
stop 
@enduml